apiVersion: v1
kind: Service
metadata:
  name: {{ template "lrc-portfolio.name" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "lrc-portfolio.name" . }}
spec:
  ports:
  - name: {{ .Values.service.portName }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ template "lrc-portfolio.name" . }}
  type: {{ .Values.service.type }}