nameOverride: lrc-portfolio
namespace: apps
serviceAccount:
  name: lrc-portfolio-reader

# Deployment settings
spec:
  replicas: 2
  restartPolicy: Always
  containerPort: 3000
  image:
    repository: lclemons
    tag: portfolio-app:v2

# Service settings
service:
  portName: http
  type: ClusterIP
  port: 3000
  targetPort: 80